# Generated by Django 3.1.7 on 2021-05-10 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0006_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='sign',
        ),
    ]
