# Generated by Django 3.1.7 on 2021-05-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0007_auto_20210510_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=9)),
                ('passw', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'login3',
            },
        ),
    ]
