# Generated by Django 3.1.7 on 2021-05-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0008_log'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sign',
            table=None,
        ),
    ]
