# Generated by Django 3.1.7 on 2021-05-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0009_auto_20210510_1544'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sign',
            table='signup',
        ),
    ]
