# Generated by Django 3.1.7 on 2021-05-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0010_auto_20210510_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sign',
            new_name='Signup',
        ),
    ]
