# Generated by Django 3.1.7 on 2021-05-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0011_auto_20210510_1557'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signup',
            table='signup2',
        ),
    ]
