# Generated by Django 3.1.7 on 2021-05-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0012_auto_20210510_1653'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signup',
            table='signup3',
        ),
    ]
