# Generated by Django 3.1.7 on 2021-05-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0013_auto_20210510_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup1',
            fields=[
                ('an', models.CharField(max_length=16, unique=True)),
                ('mn', models.CharField(max_length=11)),
                ('cid', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('cpass', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'signup4',
            },
        ),
    ]
