# Generated by Django 3.1.7 on 2021-05-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0016_personalbanking1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='personalbanking1',
            new_name='personalbanking2',
        ),
        migrations.AlterModelTable(
            name='personalbanking2',
            table='personal2',
        ),
    ]
