# Generated by Django 3.1.7 on 2021-05-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0020_transaction1'),
    ]

    operations = [
        migrations.CreateModel(
            name='electrical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=17)),
                ('cid', models.CharField(max_length=9)),
                ('Service', models.CharField(max_length=20)),
                ('bill', models.CharField(max_length=20)),
            ],
        ),
    ]
