# Generated by Django 3.1.7 on 2021-05-15 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0021_electrical'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='electrical',
            table='electrical',
        ),
    ]
