# Generated by Django 3.1.7 on 2021-05-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0023_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=9)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('mn', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=20)),
                ('loan', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'insurance',
            },
        ),
        migrations.CreateModel(
            name='insurance2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=9)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('mn', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=20)),
                ('loan', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'insurance1',
            },
        ),
        migrations.CreateModel(
            name='loanapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=9)),
                ('amt', models.CharField(max_length=20)),
                ('ir', models.CharField(max_length=20)),
                ('months', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'loan',
            },
        ),
        migrations.CreateModel(
            name='mobile2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=9)),
                ('sim', models.CharField(max_length=9)),
                ('mn', models.CharField(max_length=11)),
                ('bill', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mobile2',
            },
        ),
    ]
